experimental-features = nix-command flakes
accept-flake-config = true
connect-timeout = 5
warn-dirty = false
keep-going = true
build-users-group =
sandbox = false
flake-registry =
post-build-hook = /etc/nix/post-build-hook
