name: Nix

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: check (${{ matrix.system }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-24.04
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: DeterminateSystems/determinate-nix-action@58b42ef6cd91478a14253e00805ec7c79eb1566a # v3.22.4

      - name: Check flake
        run: |
          nix flake check --keep-going --print-build-logs \
            "github:${{ github.repository }}/${{ github.sha }}"
